### ISSUE TITLE
BTF bfit fails in R 3.2.3 for linux

### ISSUE THREAD

**Issue by idrovenice** [roualdes/btf#1]
Dear all,

nice library, compliments. I would like to give it a try.
I was just trying to run the following small script taken from examples:

```
# Cubic trend filtering
# from genlasso::trendfilter
## Not run: 
require(btf)
n <- 100
beta0 = numeric(100)
beta0[1:40] <- (1:40-20)^3
beta0[40:50] <- -60*(40:50-50)^2 + 60*100+20^3
beta0[50:70] <- -20*(50:70-50)^2 + 60*100+20^3
beta0[70:100] <- -1/6*(70:100-110)^3 + -1/6*40^3 + 6000
beta0 <- -beta0
beta0 <- (beta0-min(beta0))*10/diff(range(beta0))
y <- beta0 + rnorm(n)
bfit <- btf(y=y, k=3)
plot(bfit, col='grey70')
## End(Not run)

```

but the bfit step fail with the following error:

```
> bfit <- btf(y=y, k=3)
Error in gdPBTF(iter, y, k, D, alpha, rho, debug) : 
  function 'enterRNGScope' not provided by package 'Rcpp'
```

if I try to add the following at the top:

`require(Rcpp)`

the script does not give any error but it does not return the prompt.
It is basically stuck and runs without stopping.

Are you aware of this problem?
Kindly let me know.

Thanks.
Best regards.

**Comment by roualdes** [comment]
Didn't know about it.  

I attempted to fix this error and I've pushed the changes to this repository, but not on CRAN.  Would you re-install from this repository and see if you still encounter the error?  Let me know. Thanks.

**Comment by idrovenice** [comment]
Now it works, thanks a lot.
I only have a short question: why in the manual the instruction n<-100 is commented out?
You have the following at page 2:

`## Not run: n <- 100`

Is that for a special reason or it it just a typo?
Thanks again.
I will try to use the features of this package.
Regards.
Cheers.

**Comment by roualdes** [comment]
Typo.  Thanks.  Should be fixed now.

Cheers.
